site_name: Discordomicon
site_description: A documentation for evil things Discord.

repo_name: Contribute on GitHub
repo_url: https://github.com/discordomicon/discordomicon.github.io

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

extra:
  homepage: removal/overview
  generator: false

nav:
  - âŒ Data Removal:
    - Overview: removal/overview.md
    - ğŸ” Preparing data for request: 
      - Request package: removal/package.md
      - Convert to required format: removal/convert.md
    - ğŸ“œ Ticket Templates: 
      - GDPR: removal/GDPR.md
      - UK-GDPR: removal/UK-GDPR.md
    - ğŸ’¬ Creating a support ticket: removal/ticket.md
    - â” FAQ: removal/FAQ.md
  - ğŸŒ Community:
    - Discussions: community/discussions.md

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Copy link to this section
